<a href="https://colab.research.google.com/github/pavankumarchowdary35/NLP-projects/blob/main/Models%26tokenizers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install tokenizers

In [2]:
from transformers import AutoTokenizer

In [3]:
checkpoint = 'bert-base-uncased'
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

tokenizer_config.json:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [4]:
tokenizer

BertTokenizerFast(name_or_path='bert-base-uncased', vocab_size=30522, model_max_length=512, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}

In [6]:
tokenizer('my name is pavan kumar medarametla')

{'input_ids': [101, 2026, 2171, 2003, 6643, 6212, 9600, 19960, 5400, 11368, 2721, 102], 'token_type_ids': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}

In [7]:
tokens = tokenizer.tokenize("my name is pavan Kumar Medarametla")

In [8]:
tokens

['my', 'name', 'is', 'pa', '##van', 'kumar', 'med', '##ara', '##met', '##la']

In [9]:
ids = tokenizer.convert_tokens_to_ids(tokens)

In [10]:
ids

[2026, 2171, 2003, 6643, 6212, 9600, 19960, 5400, 11368, 2721]

In [11]:
tokenizer.convert_ids_to_tokens(ids)

['my', 'name', 'is', 'pa', '##van', 'kumar', 'med', '##ara', '##met', '##la']

In [12]:
tokenizer.decode(ids)

'my name is pavan kumar medarametla'

In [13]:
tokenizer.encode('my name is pavan kumar medarametla')

[101, 2026, 2171, 2003, 6643, 6212, 9600, 19960, 5400, 11368, 2721, 102]

In [14]:
data = [
  "I like cats.",
  "Do you like cats too?",
]
tokenizer(data)

{'input_ids': [[101, 1045, 2066, 8870, 1012, 102], [101, 2079, 2017, 2066, 8870, 2205, 1029, 102]], 'token_type_ids': [[0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1]]}

In [15]:
from transformers import AutoModelForSequenceClassification

In [16]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [19]:
model_inputs = tokenizer("hello world", return_tensors='pt')

In [24]:
model_inputs

{'input_ids': tensor([[ 101, 7592, 2088,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1]])}

In [20]:
outputs = model(**model_inputs)         ## the default was to create a binary classifier

In [21]:
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[-0.4584,  0.3895]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [22]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint, num_labels=3)

Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [25]:
outputs = model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[0.0452, 0.2008, 0.1674]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)

In [26]:
outputs.logits

tensor([[0.0452, 0.2008, 0.1674]], grad_fn=<AddmmBackward0>)

In [27]:
outputs['logits']

tensor([[0.0452, 0.2008, 0.1674]], grad_fn=<AddmmBackward0>)

In [28]:
outputs[0]

tensor([[0.0452, 0.2008, 0.1674]], grad_fn=<AddmmBackward0>)

In [29]:
outputs.logits.detach().cpu().numpy()

array([[0.04518687, 0.20080087, 0.16743511]], dtype=float32)

In [30]:
data = [
  "I like cats.",           ### on purpose, when the data is list of texts, we need to specify padding and truncation, because texts may be of different length
  "Do you like cats too?",
]
model_inputs = tokenizer(data, return_tensors='pt')
model_inputs

ValueError: Unable to create tensor, you should probably activate truncation and/or padding with 'padding=True' 'truncation=True' to have batched tensors with the same length. Perhaps your features (`input_ids` in this case) have excessive nesting (inputs type `list` where type `int` is expected).

In [31]:
model_inputs = tokenizer(
    data, padding=True, truncation=True, return_tensors='pt')
model_inputs

{'input_ids': tensor([[ 101, 1045, 2066, 8870, 1012,  102,    0,    0],
        [ 101, 2079, 2017, 2066, 8870, 2205, 1029,  102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1]])}

In [32]:
model_inputs['input_ids']

tensor([[ 101, 1045, 2066, 8870, 1012,  102,    0,    0],
        [ 101, 2079, 2017, 2066, 8870, 2205, 1029,  102]])

In [33]:
model_inputs['attention_mask']

tensor([[1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1]])

In [34]:
outputs = model(**model_inputs)
outputs

SequenceClassifierOutput(loss=None, logits=tensor([[ 0.3416, -0.0247,  0.1859],
        [ 0.3096, -0.0246,  0.1641]], grad_fn=<AddmmBackward0>), hidden_states=None, attentions=None)